#!/bin/bash

echo "***************************"
echo "** Begin TAZ postinstall **"

echo "* fixup homedir ownership"

# make sure taz homedir ends up owned by taz, since it will
# be owned by root when created by the rootfs overlay mechanism
chown -R taz:users /home/taz

echo "* update group membership"

usermod -a -G lp,lpadmin,video,scanner taz

echo "* autostart X"

# catalyst calls X autostart from root user bashrc,
# but in our case taz user is the one that gets logged in at boot
cat /root/.bashrc >> /home/taz/.bashrc
# switch "echo startx | su - 'taz'" for plain "startx" since
# this is now executed directly by taz user
sed -i '/echo startx/ s/echo.*/startx/' /home/taz/.bashrc
cp /etc/skel/.bashrc /root/.bashrc

echo "* enable services"

rc-update add autofs default
rc-update add dbus default
rc-update add set-passwd default

echo "* configure usb automount"

# support a couple of typical partitions for now
echo "## USB automounts" >> /etc/fstab
for DEV in sda1 sdb1 ; do
  mkdir /mnt/$DEV
  touch /mnt/$DEV/.keep
  echo "/dev/$DEV /mnt/$DEV auto defaults,users,exec,sync 0 0" >> /etc/fstab
done

echo "* remove extra python"
emerge -c =dev-lang/python-3.5.5
eselect python cleanup

echo "** End TAZ postinstall **"
echo "**************************"
